# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

workspace 'Modularization'

target 'App' do
  

  target 'AppTests' do
    
  end

  target 'AppUITests' do
    
  end

end

target 'Common' do
  project '../Common/Common'

end